theme: jekyll-theme-cayman
show_downloads: false
title : Rencontres des Utilisateurs Francophones de QGIS - édition 2018
language: fr
is_user_page: false
is_project_page: false
twitter:
  username: osgeofr
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"
plugins_dir:
 - jekyll-feed
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-sitemap

summary: Conférence QGIS des utilisateurs francophones 2018 - Montpellier. 13 et 14 décembre 2018
tags: [QGIS,OSGEO,Open Source,Conférence,SupAgro,Agrotic,OSGEO-FR]
